version: '3.8'

services:
  app:
    build: .
    container_name: yii2_app
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/web
